inclavare-containers/librats

- verifiers/sgx-ecdsa/CMakeLists.txt
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> librats: solve the dependency issue in non-occlum mode

- attesters/nullattester/CMakeLists.txt
- attesters/sev-snp/CMakeLists.txt
- attesters/sgx-ecdsa/CMakeLists.txt
- attesters/tdx-ecdsa/CMakeLists.txt
- verifiers/nullverifier/CMakeLists.txt
- verifiers/sev-snp/CMakeLists.txt
- verifiers/sev/CMakeLists.txt
- verifiers/sgx-ecdsa-qve/CMakeLists.txt
- verifiers/sgx-ecdsa/CMakeLists.txt
- verifiers/tdx-ecdsa/CMakeLists.txt
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
> librats: fix non-existing ${CMAKE_BINARY_DIR}/src dir in CMakeLists.txt

- attesters/csv/collect_evidence.c
- include/librats/csv.h
Avoid download hsk_cek cert to local filesystem
> librats: download hsk_cek cert to buffer other than local filesystem

- attesters/sgx-ecdsa/CMakeLists.txt
- verifiers/sgx-ecdsa-qve/CMakeLists.txt
- verifiers/sgx-ecdsa/CMakeLists.txt
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> librats: remove the unused dependencies libraries

- attesters/csv/main.c
- attesters/nullattester/main.c
- attesters/sev-snp/main.c
- attesters/sev/main.c
- attesters/sgx-ecdsa/main.c
- attesters/sgx-la/main.c
- attesters/tdx-ecdsa/main.c
- verifiers/csv/main.c
- verifiers/nullverifier/main.c
- verifiers/sev-snp/main.c
- verifiers/sev/main.c
- verifiers/sgx-ecdsa/main.c
- verifiers/sgx-la/main.c
- verifiers/tdx-ecdsa/main.c
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
> librats: add type field in rats_attester_opts_t and rats_verifier_opts_t

- attesters/csv/collect_evidence.c
- attesters/csv/main.c
- attesters/nullattester/collect_evidence.c
- attesters/sev-snp/main.c
- attesters/sev-snp/utils.h
- attesters/sev/main.c
- attesters/sev/sev.h
- attesters/sgx-ecdsa/collect_evidence.c
- attesters/tdx-ecdsa/collect_evidence.c
- core/rats_init.c
- include/librats/attester.h
- include/librats/evidence.h
- include/librats/verifier.h
- tee/sgx/untrust/sgx_ecdsa_ocall.c
- verifiers/api/rats_verifier_register.c
- verifiers/csv/main.c
- verifiers/nullverifier/verify_evidence.c
- verifiers/sev-snp/main.c
- verifiers/sev-snp/utils.c
- verifiers/sev-snp/utils.h
- verifiers/sev/main.c
- verifiers/sev/sev_utils.c
- verifiers/sev/sev_utils.h
- verifiers/sev/sevcert.c
- verifiers/sgx-ecdsa/verify_evidence.c
Signed-off-by: Shirong Hao <shirong@linux.alibaba.com>
> librats: clang format codes

- CMakeLists.txt
Fixes: #37
Signed-off-by: Liang Yang <liang3.yang@intel.com>
> librats: add build options for SGX_HW or SGX_SIM

- CMakeLists.txt
- api/librats_collect_evidence.c
- api/librats_verify_evidence.c
- core/base64.c
- core/cJSON.c
- include/internal/base64.h
- include/internal/cJSON.h
- include/librats/api.h
- include/librats/err.h
- include/librats/evidence.h
- tee/sgx/trust/rats_syscalls.c
> librats: add json support in APIs

- CMakeLists.txt
- cmake/CompilerOptions.cmake
- cmake/CustomInstallDirs.cmake
> librats: compatible with CMake of wamr

- tee/sgx/untrust/sgx_ecdsa_ocall.c
> librats: add missing declare of rats_global_log_level in SGX mode

- core/rats_init.c
> librats: correct the number of attesters and verifiers in SGX mode

- api/librats_collect_evidence.c
- api/librats_verify_evidence.c
- core/base64.c
- include/internal/base64.h
- verifiers/csv/main.c
- wasm/wasm.cpp
> librats: support new APIs in wasm compilation mode

- MAINTAINERS
- Makefile
- README.md
- dist/Makefile
- dist/rpm/librats-filelist
- dist/rpm/librats-sgx-filelist
- dist/rpm/librats.spec.in
Signed-off-by: Sinuo Liu <984354607@qq.com>
> librats: add rpm support in anolis 8

- CMakeLists.txt
- attesters/csv/collect_evidence.c
- attesters/internal/rats_attester_load_all.c
- attesters/nullattester/main.c
- attesters/sgx-ecdsa/main.c
- attesters/sgx-la/main.c
- core/rats_common.c
- core/rats_init.c
- include/edl/rats_syscalls.edl
- verifiers/nullverifier/main.c
- verifiers/sgx-ecdsa-qve/main.c
- verifiers/sgx-ecdsa/main.c
- verifiers/sgx-la/main.c
> librats: fix the attester selection bug in sgx mode

- .github/workflows/docker/Dockerfile-compilation-testing-anolis8.4
Signed-off-by: Sinuo Liu <984354607@qq.com>
> .github/workflows: add anolis 8.4 dockerfile for compilation testing

- .github/workflows/manually_compilation_testing_image.yml
Signed-off-by: Sinuo Liu <984354607@qq.com>
> .github/workflows: add test images for compilation check

- .github/workflows/pr_basic_compilation_check.yml
Signed-off-by: Sinuo Liu <984354607@qq.com>
> .github/workflows: add compilation test of the source code

- core/cJSON.c
- core/rats_common.c
- include/internal/core.h
- tee/sgx/trust/rats_syscalls.c
> librats: fix the conflicts with wamr

- core/cpu.c
If the guest is running under hygon platform, the sevguest check should fail
> librats: Distinguish cpu vendor when determine sev and csv support

- api/librats_collect_evidence.c
> librats: fix the bug in librats_collect_evidence

- .gitignore
- wasm/wamr/README.md
- wasm/wamr/sample/CMakeLists.txt
- wasm/wamr/sample/main.c
> librats: add sample of wamr support
